# language: csharp
# mono: none
# dotnet: 7.0.100-preview.2

# before_script:
#   - cd ~/TestDealHub

# script:
#   - dotnet restore
#   - dotnet build
#   - dotnet test

os: linux
dist: focal
language: csharp
mono: none
dotnet: 7.0.100-preview.1

script:
  - dotnet restore
  - dotnet build
  - dotnet test
