# language: csharp
# mono: none
# dotnet: 7.0.100-preview.2

# before_script:
#   - cd ~/TestDealHub

# script:
#   - dotnet restore
#   - dotnet build
#   - dotnet test

language: csharp
solution: ShoppingCart.sln

matrix:
  include:
    - os: linux
      dist: focal
      dotnet: 7.0.100
      mono: none

# Add more platforms as needed

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test

