version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    working_directory: ~/TestDealHub
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test
