version: 2.1
jobs:
  build:
    docker:
      - image: circleci/dotnet:6.0.100-sdk
    working_directory: ~/TestDealHub
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "MyProject.sln" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: dotnet restore
      - save_cache:
          key: v1-dependencies-{{ checksum "MyProject.sln" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: Build Solution
          command: dotnet build --configuration Release
      - run:
          name: Run Tests
          command: dotnet test UnitTestProject1/UnitTestProject1.csproj
      - run:
          name: Publish Artifact
          command: dotnet publish --configuration Release --output ./publish
          when: always
      - store_artifacts:
          path: ./publish
          destination: TestDealHub
  
